### ISSUE TITLE
Javascript Issue

### ISSUE THREAD

**Issue by kashyap-shah** [kashyap-shah/Snake-Game#1]
## Want Help!
When we start a game, at that time the position of food randomly comes in the position where our snake's head position is at start and game is over without being played. 
What to do for not coming food at the snake's head position at start of the game only?
https://www.github.com/kashyap-shah/Snake-Game

**Comment by skinnerap** [comment]
I'll fix it for you, give me a few minutes to look at the code.

**Comment by skinnerap** [comment]
I submitted a pull request, it is fixed.

**Comment by kashyap-shah** [comment]
Hello @skinnerap !
Thanks for your interest, but I haven't got any pull request.

**Comment by skinnerap** [comment]
Look at the pull requests tab next to "code" "issues" etc

**Comment by kashyap-shah** [comment]
Got it.

**Comment by skinnerap** [comment]
Let me know if you need help merging the pull request. I didn't delete any code, I only added a few lines.

**Comment by kashyap-shah** [comment]
Hey Thanks!
I know how to merger PR.
Can you say why you take '100' value for food.x position?

**Comment by kashyap-shah** [comment]
Hey Thanks!
I know how to merge PR.
Can you say why you take above or below '100' value to change food.x position?

**Comment by skinnerap** [comment]
Consider the situation where the food spawns at a random position, and the snake spawns at the exact same position. Call the position (120, 120). X=120 and Y=120.

Now, we have to move either the x or y coordinates of either the food or the snake. I choose the x coordinate of the food. 

You can move this coordinate a variety of ways. To guarantee we don't assign it the same value or a value that is out of bounds we use a simple if else check before assisning it a new value. 

If (the current value is greater than 100)
Then (give it any value under 100)
Else (the value is less than 100)
Then (give it any value over 100 that is still in bounds).

I choose 100 as a boundry because I knew that 100 is in bounds.

In this example the snake and food spawned at position (120, 120). So I changed food to (50, 120). Now they are on different positions and the game can begin without errors.

**Comment by skinnerap** [comment]
100 is an arbitrary value, you can pick any number that is in bounds as the boundary on your if else check.

**Comment by kashyap-shah** [comment]
Okay Got it, You are doing amazing work. 😃 
# Thank you very much @skinnerap . 👍

**Comment by skinnerap** [comment]
You are very welcome! If you have a moment to star any of my repo's that you like that would be awesome! I encourage you to fork them and explore the code on your local machine as well 👍
